project = "IoT NooB"
title = "物联小白"
description = "物联小白API文档"
format = "discount"
backtick_references = false
file = "ldoc.lua"
dir = "public"
readme = "manual.md"
style = "!new"
kind_names = {
   topic = "Manual",
   script = "Programs"
}
examples  =  {
   "tests/styles/colon.lua",
   "tests/styles/four.lua",
   "tests/styles/three.lua",
   "tests/styles/multiple.lua",
   "tests/example/mylib.c",
   "tests/moonscript/List.moon",
}