name: Lua Check

on: [push, pull_request]

jobs:

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: --globals PROJECT VERSION _ sys log gpio uart can netdrv pack json _ string rtos mcu mobile lcd mqtt io socket u8g2 audio i2c i2s spi fatfs libgnss pm pwm rtc adc crypto iotauth fskv 
