name: Lua Check

on: [push, pull_request]

jobs:

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: . -u -a --globals PROJECT VERSION PRODUCT_KEY _ sys log gpio uart can netdrv pack json _ string rtos mcu mobile lcd mqtt io socket u8g2 audio i2c i2s spi fs fatfs libgnss pm pwm rtc adc crypto iotauth fskv fastlz libfota2 http wdt bit
